name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p FailedRenderTests
    - run: echo hello > FailedRenderTests/hello.txt
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - run: mkdir -p FailedRenderTests
    - run: echo goodbye > FailedRenderTests/goodbye.txt
    - uses: actions/upload-artifact@v2
      with:
        name: FailedRenderTests
        path: FailedRenderTests
